@startuml
start
fork
    :Multiple programmers write a program;
fork again
:Multiple programmers write a program;
fork again
:Multiple programmers write a program;
  end fork

fork
  :Many users run the program;
fork again
:Many users run the program;
fork again
:Many users run the program;
end fork
end
@enduml
