@startuml
class Observer {
    update()
}

class Subject {
    observers
    attach(Observer)
    detach(Observer)
    notify()
}

Observer <|-- Controller

Subject <|-- Model
Subject <|-- View

Subject --> "Update" Observer

Model --> "Notify" Model
View --> "Notify" View

Controller --> Model
Controller --> View

@enduml
