@startuml
actor Bob

Controller -> View: attach()
Bob -> View: Push Button
View -> View: notify()
View -> Controller: update()
Controller -> Model ++ : get_random_word()
Model --> Controller --
Controller -> View: set_button_text();

@enduml