@startuml
class Observer {
    update()
}

class Subject {
    observers
    notify()
    attach(Observer)
    detach(Observer)

}
note right of Subject::notify
    for all o in observers {
        o->update()
    }
end note

class ConcreteSubject {
    observers
    attach(Observer)
    detach(Observer)
    notify()
    update()
}

class ConcreteObserver {
    update()
}

Observer <|-- ConcreteObserver

Subject <|-- ConcreteSubject

Subject --> Observer

ConcreteObserver --> ConcreteSubject

@enduml
